# **INSERTED DATA ANALYSIS**

In this file we will analyze the data that we have inserted into our database, to check if it is correct and if it has any missing values. We will also check if the data is consistent with the original data that we downloaded from the Nord Pool website.

In [9]:
import sqlite3
import pandas as pd

db_path = r"C:\Users\HUGO\Desktop\Q8 - NORUEGA\TFG\tfg\NordPoool\data\thesis_database.db"

conn = sqlite3.connect(db_path)

## **PRICES**

Total number of price records inserted: 1.007.980

In [10]:
query = """
SELECT COUNT(*)
FROM prices;
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0   1007980

### **2020**

The amount of price records should be the following: 

- 366 days * 24 hours * 20 price areas = 175.680 records

In [11]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2020-01-01'
  AND delivery_day  <  '2021-01-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    175680

### **2021**

The amount of price records should be the following: 

- 365 days * 24 hours * 20 price areas = 175.200 records

In [12]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2021-01-01'
  AND delivery_day  <  '2022-01-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    175200

### **2022**

The amount of price records should be the following: 

- 365 days * 24 hours * 20 price areas = 175.200 records

In [13]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2022-01-01'
  AND delivery_day  <  '2023-01-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    175200

### **2023**

The amount of price records should be the following: 

- 365 days * 24 hours * 20 price areas = 175.200 records

In [14]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2023-01-01'
  AND delivery_day  <  '2024-01-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    175200

### **2024**

The amount of price records should be the following: 

- 366 days * 24 hours * 20 price areas = 175.680 records

In [15]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2024-01-01'
  AND delivery_day  <  '2025-01-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    175680

### **2025**

The amount of price records should be the following: 

- 272 days * 24 hours * 20 price areas = 130.560 records
- 1 day * 23 hours * 20 price areas = 460 records
- Total = 131.020 records

In this case we don't have the day when we advance the time one hour (26th of October), so we can't balance this day with the one when we delay the time hour and we have 25 hours.

In [17]:
query = """
SELECT COUNT(*)
FROM prices
WHERE delivery_day  >= '2025-01-01'
  AND delivery_day  <  '2025-10-01';
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0    131020

We have 2 yeares (2020 and 2024) with 175.680 records, 3 years (2021, 2022 and 2023) with 175.200 records and 1 year (2025) with 131.020 records, which gives us a total of 1.007.980 records, which is the correct amount of records that we have inserted into our database.