## 🔹Imports and setup

In [12]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.data_pipeline import DatabaseManager, DataLoader, Preprocessor

db_path = Path("../NordPoool/data/thesis_database.db")

db = DatabaseManager(db_path)
loader = DataLoader(db)
pre = Preprocessor()

## 🔹Load data

In [8]:
df_prices = loader.load_prices()
df_volumes = loader.load_volumes()
df_flows = loader.load_flows()
df_capacities = loader.load_capacities()
df_zones = loader.load_bidding_zones()

## 🔹 CHECK 1: Shapes

In [9]:
print("Prices:", df_prices.shape)
print("Volumes:", df_volumes.shape)
print("Flows:", df_flows.shape)
print("Capacities:", df_capacities.shape)
print("Zones:", df_zones.shape)

Prices: (1007980, 5)
Volumes: (350880, 6)
Flows: (230470, 6)
Capacities: (0, 7)
Zones: (20, 4)

## 🔹CHECK 2: Columns

In [10]:
print("Prices columns:", df_prices.columns)
print("Volumes columns:", df_volumes.columns)
print("Flows columns:", df_flows.columns)
print("Capacities columns:", df_capacities.columns)

Prices columns: Index(['price_id', 'zone_id', 'delivery_day', 'hour', 'price_value'], dtype='object')
Volumes columns: Index(['volume_id', 'zone_id', 'delivery_day', 'hour', 'buy_volume_value',
       'sell_volume_value'],
      dtype='object')
Flows columns: Index(['flow_id', 'from_zone_id', 'to_zone_id', 'delivery_day', 'hour',
       'flow_value'],
      dtype='object')
Capacities columns: Index(['capacity_id', 'capacity_code', 'from_zone_id', 'to_zone_id',
       'delivery_day', 'hour', 'capacity_value'],
      dtype='object')

## 🔹CHECK 3: Detect datetime columns

In [11]:
df_prices.head()

   price_id  zone_id delivery_day  hour  price_value
0         1        1   2020-01-01     0        28.78
1         2        2   2020-01-01     0        28.78
2         3        3   2020-01-01     0        28.78
3         4        4   2020-01-01     0        41.88
4         5        5   2020-01-01     0        41.88

## 🔹CHECK 4: Create datetime

In [14]:
import pandas as pd

df_prices["datetime"] = pd.to_datetime(df_prices["delivery_day"]) + pd.to_timedelta(df_prices["hour"], unit="h")

df_prices[["delivery_day", "hour", "datetime"]].head()

  delivery_day  hour   datetime
0   2020-01-01     0 2020-01-01
1   2020-01-01     0 2020-01-01
2   2020-01-01     0 2020-01-01
3   2020-01-01     0 2020-01-01
4   2020-01-01     0 2020-01-01

## 🔹 CHECK 5: Correct datetime

In [15]:
print(df_prices["datetime"].min())
print(df_prices["datetime"].max())

2020-01-01 00:00:00
2025-09-30 23:00:00